### ISSUE TITLE
slack join link has expired

### ISSUE THREAD

**Issue by stevekrouse** [malloydata/malloydata.github.io#11]
![Screenshot 2023-02-09 at 4 42 52 PM](https://user-images.githubusercontent.com/2288939/217945864-eacdcddf-fc8a-4b19-aac5-37b5102c72b6.png)

https://github.com/malloydata/malloydata.github.io/blob/752f6ba1960325e18c7fa3fc707a44a1db4bc72a/docs/_src/index.md?plain=1#L18

**Comment by bporterfield** [comment]
yeesh 😵‍💫 thanks Steve!
