### ISSUE TITLE
Need to be able to link to sections on other docs

### ISSUE THREAD

**Issue by mtoy-googly-moogly** [malloydata/malloydata.github.io#97]
WORKS: `[#sectionInThisDoc]`
WORKS: `[../path/to/other_doc.malloynb]`

DOESN'T WORK: `[../path/to/other_doc.malloynb#section]`

**Comment by christopherswenson** [comment]
Do you have a specific example of where this is not working? There are many instances of this pattern being used in docs today. 

When you say "doesn't work," do you mean that the link checker complains, or that the link just doesn't jump to the correct section?

**Comment by mtoy-googly-moogly** [comment]
ok i think i understand what is going on, i will close this bug, don't like it. but i can live with it.
